name: liquidation schedule

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:
    branches: [main]
jobs:
  liquidator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install ts
        run: npm install -g typescript ts-node
      - name: Install Dependencies
        run: npm i
      - name: build liquidator
        run: npm run build
      - name: set env
        run: |
          export PRIV_KEY=${{ secrets.PRIV_KEY }}
          export APP=production
          export THROTTLE=1900
        # Uncomment line below and specify lending market if you only want to target a single pool
        # export MARKET=4UpD2fh7xH3VP9QQaXtsS1YY3bxzWhtfpks7FatyKvdY
      - name: run liquidator
        run: npm run start
